import VirtualRubiksCube
from numpy import *

#Cruz blanco + rojo:
def pz_blanco_rojo(w, r, y, o, b, g):
    if w[1,2] == "w" and g[2,1] == "r":
        print("dp")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.down_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif w[2,1] == "w" and o[0,1] == "r":
        print("2d")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.down(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.down(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif w[1,0] == "w" and b[2,1] == "r":
        print("d")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.down(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif w[0,1] == "r" and r[2,1] == "w":
        print("d, r, f")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.down(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.right(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif w[1,2] == "r" and g[2,1] == "w":
        print("r, f")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.right(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif w[2,1] == "r" and o[0,1] == "w":
        print("b, r, dp")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.back(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.right(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.down_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif w[1,0] == "r" and b[2,1] == "w":
        print("lp, fp")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.left_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif r[1,2] == "r" and g[1,0] == "w":
        print("f")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif r[1,2] == "w" and g[1,0] == "r":
        print("rp, dp")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.right_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.down_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif r[1,0] == "r" and b[1,2] == "w":
        print("fp")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif r[1,0] == "w" and b[1,2] == "r":
        print("l, d")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.left(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.down(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif g[1,2] == "r" and o[1,2] == "w":
        print("r, dp")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.right(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.down_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif g[1,2] == "w" and o[1,2] == "r":
        print("2r, f")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.right(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.right(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif b[1,0] == "r" and o[1,0] == "w":
        print("lp, d")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.left_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.down(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif b[1,0] == "w" and o[1,0] == "r":
        print("2l, fp")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.left(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.left(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif y[2,1] == "w" and r[0,1] == "r":
        print("2f")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif y[2,1] == "r" and r[0,1] == "w":
        print("u, l, fp")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.up(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.left(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif y[1,2] == "w" and g[0,1] == "r":
        print("u, 2f")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.up(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif y[1,2] == "r" and g[0,1] == "w":
        print("rp, f")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.right_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif y[1,0] == "w" and b[0,1] == "r":
        print("up, 2f")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.up_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif y[1,0] == "r" and b[0,1] == "w":
        print("l, fp")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.left(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif y[0,1] == "w" and o[2,1] == "r":
        print("2u, 2f")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.up(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.up(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    elif y[0,1] == "r" and o[2,1] == "w":
        print("u, rp, f")
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.up(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.right_prima(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
        wx = array(w)
        rx = array(r)
        yx = array(y)
        ox = array(o)
        bx = array(b)
        gx = array(g)
        VirtualRubiksCube.front(w, r, y, o, b, g, wx, rx, yx, ox, bx, gx)
    else:
        print("pz_blanca_rojo ya en lugar")
